{
 "title": "Air Quality - time_bucket()",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Current Windspeed at Risavika (VS1721) ms",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT last(wind_speed, timestamp) FROM wind_measurements where station_id = 'VS1721'"
    }
   ]
  },
  {
   "title": "Windspeed high resolution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, wind_speed, station_id FROM wind_measurements\nWHERE\n$__timeFilter(timestamp) ORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Step 1",
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "options": {
    "content": "\n# Getting started with time_bucket()\n\nThe `time_bucket()` function was one of the first time-series specific functions built into TimescaleDB. It was designed to make it easier to aggregate metrics into \"time buckets\" and allows greater querying flexibility than the functions that already exist within PostgreSQL. Specifically, the `date_trunc()` function is limited in only being able to select by a single time unit. For example, you can query for 1 minute, 1 day, 1 month, or 1 year. `time_bucket()` allows you to define arbitrary time buckets - think 1 minute, 5 minutes, 1 day, 14 days, etc. \n\nThe syntax for this function is very straight forward - you essentially embed the function directly in a select statement. Let's try a simple example using the Air Quality sample application. This application pulls data from an open API, assigns unique ids for different locations and parameter types, and stores the measurement value obtained from different sensors. Let's say that we want to find all measurements associated with `location_id = 1`. \n\n`SELECT * FROM measurements WHERE location_id = 150;`\n\nYou'll notice that Grafana has nicely graphed each parameter in a separate color. You can achieve this by setting the metric value to `parameter_id`.\n\n\n\n"
   }
  },
  {
   "title": "Wind Direction high resolution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, wind_direction, station_id FROM wind_measurements\nWHERE\n$__timeFilter(timestamp) ORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Wind Direction Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT bucket as time, station_id, avg_direction as wind_direction FROM wind_measurements_15min WHERE $__timeFilter(bucket) ORDER BY 1"
    }
   ]
  },
  {
   "title": "Wind Speed Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT bucket as time, station_id, avg_speed as wind_speed, max_speed, min_speed FROM wind_measurements_15min WHERE $__timeFilter(bucket) ORDER BY 1"
    }
   ]
  },
  {
   "title": "4 hour average for Location 150",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('4 hours', time) AS \"time\",\n  parameter_id::TEXT AS metric,\n  avg(value)\nFROM measurements\nWHERE\n  $__timeFilter(\"time\") AND \n  location_id = 150\nGROUP BY 1, 2\nORDER BY 1, 2"
    }
   ]
  },
  {
   "title": "4 hour LOCF average for Location 150",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill('4 hours', time) AS \"time\",\n  parameter_id::TEXT AS metric,\n  locf(avg(value))\nFROM measurements\nWHERE\n  $__timeFilter(\"time\") AND \n  location_id = 150\nGROUP BY 1, 2\nORDER BY 1, 2"
    }
   ]
  }
 ]
}